"use client";

import { motion } from "framer-motion";
import CountUp from "react-countup";
import {
  FaIndustry,
  FaTools,
  FaHandshake,
  FaTruck,
  FaChartLine,
  FaOilCan,
  FaBalanceScale,
  FaWater,
  FaVial,
} from "react-icons/fa";

/* ================= TYPES ================= */

type MilestoneType = {
  year: string;
  title: string;
  desc: string;
  icon: React.ElementType; // ✅ modern & future-proof
};

/* ================= YEAR CONFIG ================= */

const startYear = 2020;
const currentYear = new Date().getFullYear();

/* ================= MILESTONES ================= */

const milestones: MilestoneType[] = [
  {
    year: "2020",
    title: "Company Founded",
    desc: "Established in Sri Ganganagar with a vision to modernize dairy operations.",
    icon: FaIndustry,
  },
  {
    year: "2021",
    title: "Product Launch & Sales Start",
    desc: "Introduced milk analyzers, milking machines, DPUs, and cream separators.",
    icon: FaTools,
  },
  {
    year: "2022",
    title: "Authorized Distributor",
    desc: "Recognized as an authorized distributor of K R Electronics Industries.",
    icon: FaHandshake,
  },
  {
    year: "2023",
    title: "Regional Expansion",
    desc: "Expanded sales and service network across North Rajasthan.",
    icon: FaTruck,
  },
  {
    year: "2024",
    title: "Trusted Industry Partner",
    desc: "Built long-term trust through reliable products and expert service.",
    icon: FaChartLine,
  },
  {
    year: "2025",
    title: "Advanced Dairy Solutions",
    desc: "Introduced new technology and enhanced after-sales service support.",
    icon: FaTools,
  },
  {
    year: "2026",
    title: "Expanding Across Rajasthan",
    desc: "Strengthening our presence with more installations and service locations.",
    icon: FaChartLine,
  },
];

/* ================= AUTO GENERATE MISSING YEARS ================= */

const existingYears = milestones.map((m) => Number(m.year));

const autoGeneratedYears: MilestoneType[] = [];

for (let year = startYear; year <= currentYear; year++) {
  if (!existingYears.includes(year)) {
    autoGeneratedYears.push({
      year: year.toString(),
      title: year === currentYear ? "Growing Strong" : "Business Growth",
      desc:
        year === currentYear
          ? "Continuously delivering advanced dairy solutions with trusted service support."
          : "Expanding our reach and improving services.",
      icon: FaChartLine,
    });
  }
}

/* ================= FINAL TIMELINE ================= */

const finalMilestones = [...milestones, ...autoGeneratedYears].sort(
  (a, b) => Number(a.year) - Number(b.year)
);

/* ================= STATS ================= */

const stats = [
  { label: "Years of Experience", value: currentYear - startYear },
  { label: "Products Installed", value: 500 },
  { label: "Products & Genuine Spare Parts", value: 50 },
  { label: "Happy Clients", value: 3000 },
  { label: "Service Locations", value: 25 },
];

/* ================= INSTALLATIONS ================= */

const installations: MilestoneType[] = [
  {
    year: "",
    title: "Milk Analyzer Installation",
    desc: "Accurate milk testing solutions installed at collection centers and dairies.",
    icon: FaVial,
  },
  {
    year: "",
    title: "Milking Machine Setup",
    desc: "Professional installation of Vansun milking machines for farms.",
    icon: FaOilCan,
  },
  {
    year: "",
    title: "Milk Collection Unit (DPU)",
    desc: "End-to-end installation of dairy khata & milk collection units.",
    icon: FaBalanceScale,
  },
  {
    year: "",
    title: "Cream Separator Machine",
    desc: "Efficient cream separator installation with calibration support.",
    icon: FaWater,
  },
];

/* ================= COMPONENT ================= */

export default function MilestonesTimeline() {
  return (
    <section className="relative overflow-hidden">

      {/* BACKGROUND */}
      <div className="absolute inset-0 -z-10 bg-gradient-to-b from-teal-50 via-white to-white dark:from-[#0f172a] dark:via-[#020617] dark:to-[#020617]" />

      <div className="max-w-7xl mx-auto px-6 pb-32">

        {/* DESKTOP TIMELINE */}
        <div className="hidden md:block pt-20">
          <div className="relative flex flex-wrap justify-center gap-y-12">

            <div className="absolute top-7 left-0 right-0 h-[2px] bg-gradient-to-r from-transparent via-teal-500 to-transparent" />

            {finalMilestones.map((item) => {
              const Icon = item.icon;

              return (
                <motion.div
                  key={item.year + item.title}
                  initial={{ opacity: 0, y: 40 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  className="w-1/5 min-w-[180px] px-3 text-center"
                >
                  <div className="mx-auto mb-4 w-14 h-14 rounded-full bg-teal-600 text-white flex items-center justify-center shadow-lg shadow-teal-600/30">
                    <Icon className="w-5 h-5" />
                  </div>

                  <span className="text-sm font-semibold text-teal-600">
                    {item.year}
                  </span>

                  <h3 className="mt-2 text-lg font-semibold">{item.title}</h3>

                  <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
                    {item.desc}
                  </p>
                </motion.div>
              );
            })}
          </div>
        </div>

        {/* MOBILE TIMELINE */}
        <div className="md:hidden mt-20 space-y-12 relative">

          <div className="absolute left-5 top-0 bottom-0 w-[2px] bg-gradient-to-b from-transparent via-teal-500 to-transparent" />

          {finalMilestones.map((item) => {
            const Icon = item.icon;

            return (
              <motion.div
                key={item.year + item.title}
                initial={{ opacity: 0, x: -40 }}
                whileInView={{ opacity: 1, x: 0 }}
                viewport={{ once: true }}
                className="pl-16 relative"
              >
                <div className="absolute left-0 w-10 h-10 rounded-full bg-teal-600 text-white flex items-center justify-center">
                  <Icon className="w-4 h-4" />
                </div>

                <span className="text-sm font-semibold text-teal-600">
                  {item.year}
                </span>

                <h3 className="mt-1 text-lg font-semibold">{item.title}</h3>

                <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
                  {item.desc}
                </p>
              </motion.div>
            );
          })}
        </div>

        {/* STATS */}
        <section className="mt-36">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            {stats.map((stat) => (
              <motion.div
                key={stat.label}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                viewport={{ once: true }}
                className="bg-white/80 dark:bg-[#020617]/80 backdrop-blur-md border rounded-2xl p-6 shadow-lg"
              >
                <div className="text-3xl font-bold text-teal-600">
                  <CountUp end={stat.value} duration={2} enableScrollSpy scrollSpyOnce />+
                </div>

                <p className="mt-2 text-sm font-medium text-gray-700 dark:text-gray-400">
                  {stat.label}
                </p>
              </motion.div>
            ))}
          </div>
        </section>

        {/* INSTALLATIONS */}
        <section className="mt-36">
          <h2 className="text-3xl font-bold text-center mb-12">
            Product Installations
          </h2>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-8">

            {installations.map((item) => {
              const Icon = item.icon;

              return (
                <motion.div
                  key={item.title}
                  initial={{ opacity: 0, y: 30 }}
                  whileInView={{ opacity: 1, y: 0 }}
                  viewport={{ once: true }}
                  className="bg-white/80 dark:bg-[#020617]/80 backdrop-blur-md border rounded-2xl p-6 text-center shadow-lg hover:shadow-xl transition"
                >
                  <div className="mx-auto mb-4 w-12 h-12 rounded-full bg-teal-600 text-white flex items-center justify-center">
                    <Icon className="w-5 h-5" />
                  </div>

                  <h3 className="font-semibold text-lg">{item.title}</h3>

                  <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
                    {item.desc}
                  </p>
                </motion.div>
              );
            })}

          </div>
        </section>

      </div>
    </section>
  );
}
